[package]
name = "ActiveBreach"
version = "0.1.0"
edition = "2021"
license = "CC-BY-NC-4.0"
repository = "https://github.com/crisisevasion/syscall-proxy"

[dependencies]
lazy_static = "1.5.0"
once_cell = "1.21.1"
winapi = { version = "0.3", features = [
    "ntdef", "winbase", "minwindef", "handleapi", "winnt",
    "sysinfoapi", "fileapi", "processthreadsapi", "memoryapi",
    "synchapi", "errhandlingapi", "libloaderapi"
] }

[lib]
name = "ActiveBreach"
crate-type = ["cdylib"]
path = "src/lib.rs"

[[bin]]
name = "breacher"
path = "test/entry.rs"

[profile.release]
lto = true
opt-level = 3
debug = false
strip = "symbols"
panic = "abort"
codegen-units = 1
incremental = false

[profile.dev]
lto = true
opt-level = 0
debug = true
