[package]
name = "activebreach"
project = "syscall-proxy"
version = "0.1.0"
author = "CrisisEvasion, DutchPsycho"
organization = "TITAN Softwork Solutions"
license = "CC-BY-NC-4.0"
repository = "https://github.com/crisisevasion/syscall-proxy"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
winapi = { version = "0.3", features = ["ntdef", "winbase", "minwindef", "handleapi", "winnt", "sysinfoapi", "fileapi", "processthreadsapi", "memoryapi", "synchapi", "errhandlingapi", "libloaderapi"] }

[lib]
name = "activebreach"
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
opt-level = 3
debug = false
strip = "symbols"
panic = "abort"
codegen-units = 1
incremental = false
